name: attinf-explanations
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3
  - matplotlib
  - captum
  - pandas
  - pytorch=1.6.0
  - scipy
  - torchvision
  - pip
  - pip:
    - scikit-learn
    - requests
